### PR TITLE
fix(backport): exclude utm_term from collection

### LINKED ISSUE #153: Capturing utm_term may potentially leak PII
The `utm_term` is typically populated from search queries and can theoretically leak PII. So it's safest to exclude it from collection for now the same way we already exclude the `utm_id` one.

### PR DESCRIPTION
**Pull request by ramboz**
The utm_term is typically populated from search queries and can theoretically leak PII. So it's safest to exclude it from collection for now

Fix #153

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -186,7 +186,7 @@ new PerformanceObserver((list) => {
 
 [...new URLSearchParams(window.location.search).entries()]
   .filter(([key]) => key.startsWith('utm_'))
-  .filter(([key]) => key !== 'utm_id')
+  .filter(([key]) => key !== 'utm_id' && key !== 'utm_term')
```
Comment (trieloff) [inline src/index.js:189]:
```suggestion
  .filter(([key]) => key !== 'utm_id')
  .filter(([key]) => key !== 'utm_term')
```

**Review by trieloff — APPROVED** [review]
